spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamsoft_project?useUnicode=true&serverTimezone=Europe/Minsk
    username: admin
    password: qwe1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    changeLog: classpath:/changelog/db.changelog-master.yaml